package lin.community.communtiy.mapper;

import java.util.List;
import lin.community.communtiy.model.Mylike;
import lin.community.communtiy.model.MylikeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MylikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYLIKE
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    long countByExample(MylikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYLIKE
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    int deleteByExample(MylikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYLIKE
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    int insert(Mylike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYLIKE
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    int insertSelective(Mylike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYLIKE
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    List<Mylike> selectByExampleWithRowbounds(MylikeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYLIKE
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    List<Mylike> selectByExample(MylikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYLIKE
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    int updateByExampleSelective(@Param("record") Mylike record, @Param("example") MylikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYLIKE
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    int updateByExample(@Param("record") Mylike record, @Param("example") MylikeExample example);
}