package lin.community.communtiy.model;

public class Mylike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYLIKE.USERID
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYLIKE.QUESTIONID
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    private Long questionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYLIKE.TYPE
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYLIKE.USERID
     *
     * @return the value of MYLIKE.USERID
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYLIKE.USERID
     *
     * @param userid the value for MYLIKE.USERID
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYLIKE.QUESTIONID
     *
     * @return the value of MYLIKE.QUESTIONID
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    public Long getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYLIKE.QUESTIONID
     *
     * @param questionid the value for MYLIKE.QUESTIONID
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    public void setQuestionid(Long questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYLIKE.TYPE
     *
     * @return the value of MYLIKE.TYPE
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYLIKE.TYPE
     *
     * @param type the value for MYLIKE.TYPE
     *
     * @mbg.generated Fri Apr 16 09:52:29 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }
}